#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

ambari::params::repo_url: %{cosmos::params::cosmos_repo_platform_url}
cosmos::params::cosmos_subnet: '192.168.11.0'
cosmos::params::cosmos_netmask: '255.255.255.0'
cosmos::params::cosmos_api_mode: 'dev'
cosmos::params::cosmos_repo_platform_url: 'http://cosmos10.hi.inet/nexus/service/local/yum/repos/snapshots/development'
cosmos::params::cosmos_ssl_cert_source: "puppet:///modules/cosmos/environments/%{environment}/certs/%{hostname}_cer.pem"
cosmos::params::cosmos_ssl_key_source: "puppet:///modules/cosmos/environments/%{environment}/certs/%{hostname}_key.pem"
cosmos::slave::host_key_priv_file: "puppet:///modules/cosmos/environments/%{environment}/%{hostname}_key"
cosmos::slave::ct_key_priv_file: "puppet:///modules/cosmos/environments/%{environment}/%{hostname}_ct_key"
cosmos::params::domain: '.vagrant'
cosmos::params::master_ip: '192.168.11.10'
cosmos::params::master_hostname: 'master'
cosmos::params::infinity_url: 'hdfs://cosmos-store1'
cosmos::params::pdihub_client_id: 'e86cb3c9ffd8bd51f9ec'
cosmos::params::pdihub_client_secret: '843e55ffe646e223f75fe1f6a3d6f880c3c507ce'
cosmos::params::horizon_password: 'horizon'
cosmos::openvz::network::host_iface: 'eth1'
slave_hosts:
    - 'compute1'
    - 'compute2'
    - 'store1'
    - 'store2'
