#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

cosmos::slave::rack: "rack01"
cosmos::slave::ip: "192.168.11.23"
cosmos::slave::ct_ip: "192.168.11.73"
cosmos::slave::ct_hostname: "cosmos-compute1"
cosmos::slave::ct_gateway: "192.168.11.23"
cosmos::slave::hardware_profile: g1-compute
cosmos::slave::name: "Compute 1"
cosmos::slave::ram: 1024
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJosUS666vRfCWFksro3aj7IrLznaSDtGzMR1+8ktaPdPxILAp+KItjfHbBKo47FG47NG/f9MGfHJGNyzsHkCR9zCUzAUWGhlVlWdKNeJFxNFb45xZPEdBNTnZ5VEsW5+4UeZNaYR/4V4DKf0rVOXvIaF4coqmVQvA8pnmrvdeD3AHmvDjvVSivSoGja+Nu8Qucg2AozCa4z3LC2oizYdI0E9znpp1VbPiw0z1xVzQEHTV/ylauTbI99Lc84Igfq6O8Rqju6VcyD/CluT4b421kh/kTEE5CC0rpcVZ08zNl2HihuSD+UspPhMGipWpqf+H6jt7wadKlyPRegeMVywl"
cosmos::slave::ct_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDG+9aJ4cjcx7YjfNEk3ILEeyuZfi4DbW/FUCsLAEwNrTfKthB6+xWcfXd3KUbZ1mq+2QoUYk2tLWw6kmBy15sbyPqZ8V32cFzNR5S9q8MbgUj+g8x5hrMbfwe53hV/BENRibAmGBwQFBDsNkx59ufHXwGaLZJhd/4Ph4P4GNKVBfh6dDS6WWzO2tHIg3HRo2KgyXVeL/6q5As8GG02VPXvMEoPeCGHIFDmW8qUPjaL0iAaSbRe92doxowy1rzvU4w1LwLFP7/9G4QlVZYfFqdu9nwVJpwSrUIKGalj5rvxqsrqB3RdbhesMoiSrBPEyj21/TN38qDxuwpJqiTRMiEv"
