cosmos::slave::ip: "192.168.11.21"
cosmos::slave::ct_ip: "192.168.11.71"
cosmos::slave::ct_hostname: "vagrant-store01"
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9IhUs37GT0oyxEhcHXJMa+sHqDWim88UXWpOdVWlFK+0bTSeSpaVM9u0HysYk+u49zJDXU9t8iITJII6Y3FI1HPUgmsSAGwaeK7R/QyNuU45Jl8xLu/mpzdGTlGHnVr6QMjylSyMyv9pKbiSrUPVq+WKHkwZAHmHGT4E2PjYRN4wigm6xYZMGuNmtbTEYWjlKSiAAL2I3slTVhwIA3HGuM+iW3FSb+82jh4KcBV/m+N8HY5SodUBZE2YLmIjmKrNARFJMAzziYgI/d1VZEiQeXtuvQChQy9TPJjFRp4yi8dFzoN5aZ58iDWsSRiPyHva6TyBHFFgHu9E+6PsqlDj9"
