#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

cosmos::slave::rack: "rack01"
cosmos::slave::ip: "192.168.11.21"
cosmos::slave::ct_ip: "192.168.11.71"
cosmos::slave::ct_hostname: "cosmos-store1"
cosmos::slave::ct_gateway: "192.168.11.21"
cosmos::slave::hardware_profile: hdfs-master
cosmos::slave::name: "Store 1"
cosmos::slave::ram: 1024
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9IhUs37GT0oyxEhcHXJMa+sHqDWim88UXWpOdVWlFK+0bTSeSpaVM9u0HysYk+u49zJDXU9t8iITJII6Y3FI1HPUgmsSAGwaeK7R/QyNuU45Jl8xLu/mpzdGTlGHnVr6QMjylSyMyv9pKbiSrUPVq+WKHkwZAHmHGT4E2PjYRN4wigm6xYZMGuNmtbTEYWjlKSiAAL2I3slTVhwIA3HGuM+iW3FSb+82jh4KcBV/m+N8HY5SodUBZE2YLmIjmKrNARFJMAzziYgI/d1VZEiQeXtuvQChQy9TPJjFRp4yi8dFzoN5aZ58iDWsSRiPyHva6TyBHFFgHu9E+6PsqlDj9"
cosmos::slave::ct_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCxJoyTPZwkrX+V9KERMYC07PNL2iXuiLCA3KoXSVn4XnDyUcXMeyEUHQnfRmYhQNCMNVPnhpVBGJdBLGk9PnYi6JhCVH9yj40O/0KdF1P6je4MX+JdSA4KGvT/vk5pOaD80yAYNG9Yy9TKu+7kw8Uhfncp66bRgZa3VPjOx6Ui3G3OelcmxNEzzjh9tV3qcMu9pgQc0j/Ibhs6QOfJ4PN+vH2D7x/xDpTgiRDLYdJuItNt9sjQfT1yYmK7/iDlAmPGaawsjuktfV7q4Y6m0G9H9pXIdyt5g48uhdYTczUaTX1Rm4tNuEvp5lEGwUS2atsWXXRoB/ps6Ds4r+LCdVrf"
