#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

cosmos::slave::rack: "rack01"
cosmos::slave::ip: "192.168.63.15"
cosmos::slave::ct_ip: "192.168.63.79"
cosmos::slave::ct_hostname: "andromeda-compute05"
cosmos::slave::hardware_profile: g1-compute
cosmos::slave::name: "Andromeda 05"
cosmos::slave::ram: 32768
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDI2vSTjoof+ubHupYKgSep8+VG1z4mZfZrDIu4yVojYIETXAEOn6vgMDFt+2/zhGxI6ptrM+cpa+WWRNJb3HCRW+LPfI6dZ6QrQyoZXHIMOB9P8p8PzDx722PKGR2WdmlT4O72JbQNnD+GiruF0vNZVjFpLkkGfcLxp9qX4M2mtvvuANqAdrd3An6HDrYbrLkqBepxNwl0ofqCvdsq+I4P4o2HHSkQJ1/+HHfMOtk4SNDXh37TPSoPl6oDB/CG62Q8sM2K781fu6hTzJIiVdKKnqlEqs6r1kPBo0I+DZLNZPNNmT4G9twu7iPMvD5UJmZqENQ57PSy6kyC/mvgdqr3"
cosmos::slave::ct_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWqmdZfVNghRhlVTch1kXXBznc7AviSHpjL+sFABqJTWbNZjjO3bxIrbjlhDVJHS2T7c6z0+x19bC49uwbV9f1xWcCUwPOWUbXtXRzXKFVHv56PWWYqtAo/XeeAPqSXArvcm6R4BL9fyZvO+4E26d+2aE9IBuj1IU1dX/k0d/sFa/WkKtMhCc8c3Vo4upDKifbgw887nHG3k7luNn7aLBqLQacQjoVKUezoQFWE5K4DExocQKog98/1S8+E014hQAobkj1hs8YeOoTdE9bTnK01D3hdQMM3M+VXHhq+muMcwLM/SK9lxJEpdJk62MRtlxDfpYnfNHHrrAOOEyigAWH"
