#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

cosmos::slave::ip: "192.168.63.12"
cosmos::slave::ct_ip: "192.168.63.76"
cosmos::slave::ct_hostname: "andromeda-compute02"
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCgVroeZLdAYPafPW8S3HBXcMzhexrmg3VxGYsvtFgTi2Baapw89BYy+XtDGGWrHPddcGRW5ZkwueIpvGE7z1cv42LqRWEnm6ZkWAgCKUPI8O/rqFLI3BX1OOXpwxNcdeJhbhgH9LTC56WPHPvkMjtScZiOcB2V+ptJcS0fMOgNX/kA/IGSOH2owSwBe4/Xm3E79H0Fkot77koIbjBpDz6MFYrJRIIQVuKzNrrox1rnGlON5HCc7ZwLO0Zw+aozjUFliAeyTFshCB2tvex//2JN5RiCvqXIt9vXdJBj/dp13nZu9r/XET3H2IVHsHan4k4SaclpSIdt2BRHqPbcBQbL"
