#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

cosmos::slave::ip: "192.168.63.14"
cosmos::slave::ct_ip: "192.168.63.78"
cosmos::slave::ct_hostname: "andromeda-compute04"
cosmos::slave::hardware_profile: g1-compute
cosmos::slave::name: "Andromeda 04"
cosmos::slave::ram: 32768
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZEB/dFjKLBoczSZoEUEOFbyAMWWNND03yUUQsKkXrHAvD3FtPS/3jtOUolaJpRVJkoFwR+wP3UN9xUHV7/3mU/Mf3PN7TZnnyzrG8QDvLOpZJgyQQpFvRFFuoCH6deKdVus+xIHVjcmAnqRWfpP2kX4oGN9Cmtw0+0sGOuzSGKgYGxa9EHHQ7puNUemte0g1XT25UtkGpCo7L48EyO/0qWTaH4hgjonK+u725gvcUPSxnCagqa6jLoAh7nGFQwOtiogUCm/AiamM5GS9DuCfu2doT6HxyaAbzWr/jUb5ZMpx1YAsPjKPi5QfYVpFwF9GA6C068FO7oyvm4XSUfpNh"
cosmos::slave::ct_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdR3Hd8N2W6j64NKPXKRkG6sWzByx3v5cVUS5jxjh8Q1baWzr2+NHXznX24521m2PaQ9OYhn9drkBtIo0RrpPCIQDSYIm2xTur9uOaktkhWFDdcnTj419Td8zlJ8rnvcxyoDhM0FldGrGvilTlpGsEBq3LtTbaZqmUg5t0hQ/EaBa1KEbRzk6HwZ6rX/sSqLTpIjlpnoFsrfhSganzukdA66V6wdYbkb89cunD/ruad35+Sl3V/pJF1bmJkPbUgXT0iyfH+E2zN0I8zAzg7Y26Qyk6YqzBK9l85yUV1niynxf3QfzttzasBGI4kjPW9n/HvuLCeH65NbzMq22W4ygJ"
