#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

cosmos::slave::rack: "rack01"
cosmos::slave::ip: "10.95.236.22"
cosmos::slave::ct_ip: "10.95.236.23"
cosmos::slave::ct_hostname: "andromeda-compute07"
cosmos::slave::hardware_profile: g1-compute
cosmos::slave::name: "Andromeda 07"
cosmos::slave::ram: 32768
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTGcWZpMpX6ZMT7HzAtqPhlalD0n3jVRCuLBwPzMWtRphGIIFc/kmhLzS5YEAWZaI6VouhnGSOH8rRWjbS74wsVZPuO3qYInQHvq5cfoKThf8JByxOyM/yUzynU2OyV/9nPyvQqIbFNKbCE1Cw9LxbUjdbK8m3KJGQHRJbxOzujHIpjB2wFGfG2XiKG1BKIarZdYnHZabDQl2+0VqG9Ixx71C9Nb1TfLx0xcWNwsuwcJVAxwusB/pPh/1u+T6ABuvF5Ys4/zwIxD4o5l2+dgPGh+CNaCIcfd/EVxq8h+KeBPC4s4Zpr8/kIlhQFv1ZUTl6Ys37mSS2U3ThmdRqLFah"
cosmos::slave::ct_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDwTCyo9fR8Rny/QFQUzgWTqXaFRSn1dSQGzR9/pHGVkyMoezA+f/Ep7cK3sfbDxqqHGkQWBn7uRZfbaAo8AyvmFySVr/FCHR0Rq+bT0nt8JvgxVdog7VQHWQvCBemcdIWqnuP3eREp6Ybz50kmz/YTLLAVossiLcKo5PNOWkqk25QCybXC2r0qCgndZn52F7UmD+eLVA/WqXl1Gv+R3ISfQPoCwYjO9AgyOHKj9xZ9F/UXJAd/Q4M0vSfH9Hx0TUxGX8OwLH21Zn/pBFZ/pKs7oAcf7jNLKYCuYZUvR3gyySxYTipkyCwL2kfPMLjF6+aQ1HVmoppL6w2tbRF0wp7p"
