#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

cosmos::slave::ip: "192.168.63.18"
cosmos::slave::ct_ip: "192.168.63.82"
cosmos::slave::ct_hostname: "andromeda-infinity"
cosmos::slave::hardware_profile: hdfs-master
cosmos::slave::name: "Andromeda 08"
cosmos::slave::ram: 32768
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDeoAnpD5KvdQD0xRULG+gtV0dhnBxL4bj52Ar9vWlFGj4A0n+b42qTM9nzxm9z0GHuZF9epTbfxTS3H4gEcjfwxTqLTC8PU54GLVeflKN0yZoW+1EQLy37MblPX0SgRif8RVs/nZoXl4tjG/ESyMf/+Q03oMaydXjB2rf1rXx3DWwqTqMzi6nJzKv8jfaoe3yzoPNBjZ+fWkcDa0HDykRbjEXfavccVvUUNpqqs3dh0HUmE5CnidCSRjjxKiuE07QqyoJVrP9WLAbCpCMvfyJj3j7jOOP8d0QvJv9pC4KaFcLoBeJ+R+vOtgznl0C8MRvl5jBe349XGl/VvsqtJrGN"
cosmos::slave::ct_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDhQC5Ggs6Ppyw0YLKwhZ0IlalSioFLjiaG6zVBrWnfKt/JkwC6sPaGiFhIUnosJNIkTXxp1OgA47omgnV3KedVMJMbwVSm+WYxsZR/7W5H43EpgzGt7de0wmBoj8WSNJ+KZYTUMLiycZHr4cze4RVFIXg3Q8rSwLDXDdV4vEfPlZaejsjmf3FK0ax2ASYqmESOh396CAKjruHnlGlnY/QeEkM/k7+TK8Bp+DCPlg5hZikRtIYGdvQK0IDt76/2gIu0MX3B385EPDkGWuPL2RoWfIH459qkL2i64Wyg4cfw1zF3u3TyF2CGDP1Wupgq9sFLBe7L5rDUwErXGX3R8meT"
