#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

cosmos::slave::rack: "rack01"
cosmos::slave::ip: "10.95.236.252"
cosmos::slave::ct_ip: "10.95.236.253"
cosmos::slave::ct_hostname: "andromeda-data99"
cosmos::slave::hardware_profile: hdfs-slave
cosmos::slave::name: "Andromeda 99"
cosmos::slave::ram: 8192
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDrisgGpVcK3J5rdKtmYHpySvBU7uuC3L9ysB1ZbpBXTckOazKnnQN0EnMn50RfHmrmJUDy98c6UDNVBVSt1EF1D2tq5B8xnnI97S/opHJ5EM/zXYOSgD9OvslQPu8x3Po1sSER/pOKgR8kcVYeRUHyysIM0jLA3eXidOV1wPFe1v58H5ALwIY6OZE0YFtZ5ut0DZWdJgp3+WtAACdDhT/1hMf3fSRP2lZWjQZD78TG2RtZrmr4lN2Yl+eKk3omNv0XqAdg0lgsm5C2snu4KZyHrTJ/GbxWqWXNzXDWmtK5u7kmSrOw/Zo26Sqomj4zjBsi3983OdKLPRAMAolt0Oh"
cosmos::slave::ct_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCooiQYhHWJWGsdMVD0lGlJ4bTK9PiVyKVm2q8tLQ3n4tkK6BFI7ZpmVr2n3OEARsCPNv40TGNjQ971zIneBeNXWsQlO9wuQxq+ihxqYdAaov3Qs/ybEljeP4mOln7p0FtdQELAfmtVtA4qcxjYiANiUiMXFwU5H6S5HY4Xr/fxij8ACBvd+6D9Jemy0n4MxewnauA7ApHlcwAGC2Vnp4c73bisRqrMOKdc5Gz8ARGWSKV1MFagdg53NtIpFDBK3yoMga2RzYEKGh5estXL5CsWUwaQMKxU3/QNk4oihNtfJA4W7ebQDqZBHGENj5ji78KVOtqfTNr7PF1JdCKrjW29"
