#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

ambari::params::repo_url: 'http://cosmos10.hi.inet/nexus/service/local/yum/repos/snapshots/staging'
ambari::params::repo_rpm_url: 'http://cosmos10.hi.inet/develenv/rpms/cosmos-deps/hortonworks/HDP-2.0.6.0/'
ambari::params::jdk_url: 'http://cosmos10.hi.inet/develenv/repos/bins/jdk-6u31-linux-x64.bin'
ambari::params::jce_url: 'http://cosmos10.hi.inet/develenv/repos/bins/jce_policy-6.zip'
ambari::params::hdp_utils_repo_url: 'http://servilinux.hi.inet/ambari/HDP-UTILS-1.1.0.15/'
ambari::params::hdp_utils_gpg_url: 'http://servilinux.hi.inet/ambari/RPM-GPG-KEY-Jenkins'
timezone::region: 'Europe'
timezone::locality: 'Madrid'
yum::params::yum_epel: 'http://repos.hi.inet/centos/epel%{operatingsystemmajrelease}-$basearch/RPMS.all/'
yum::params::yum_centos: 'http://repos.hi.inet/redhat/centos%{operatingsystemmajrelease}-$basearch/RPMS.all/'
yum::params::yum_centos_updates: 'http://repos.hi.inet/redhat/centos%{operatingsystemmajrelease}-$basearch/RPMS.updates'
yum::params::yum_redhat: 'http://repos.hi.inet/redhat/rhel%{operatingsystemmajrelease}s-$basearch/RPMS.all/'
yum::params::yum_redhat_optional: 'http://repos.hi.inet/redhat/rhel%{operatingsystemmajrelease}s-$basearch/RPMS.optional/'
yum::params::yum_puppet: 'http://servilinux.hi.inet/puppet/yum/el/%{operatingsystemmajrelease}/products/$basearch/'
yum::params::yum_puppet_deps: 'http://servilinux.hi.inet/puppet/yum/el/%{operatingsystemmajrelease}/dependencies/$basearch/'
cosmos::params::cosmos_repo_deps_url: 'http://cosmos10.hi.inet/develenv/rpms/cosmos-deps'
cosmos::openvz::images::base_image_url: 'http://cosmos10/develenv/repos/ovz-templates'
cosmos::openvz::images::image_name: 'centos-6-cosmos.HDP.2.0.6-20140123-x86_64.tar.gz'
cosmos::params::cosmos_subnet: '10.95.236.0'
cosmos::params::cosmos_netmask: '255.255.255.0'
cosmos::params::cosmos_ssl_cert_source: "puppet:///modules/cosmos/environments/%{environment}/certs/%{hostname}_cer.pem"
cosmos::params::cosmos_ssl_key_source: "puppet:///modules/cosmos/environments/%{environment}/certs/%{hostname}_key.pem"
cosmos::slave::gateway: '10.95.236.1'
cosmos::slave::ct_gateway: '10.95.236.1'
cosmos::slave::host_key_priv_file: "puppet:///modules/cosmos/environments/%{environment}/%{hostname}_key"
cosmos::slave::ct_key_priv_file: "puppet:///modules/cosmos/environments/%{environment}/%{hostname}_ct_key"
cosmos::params::domain: '.hi.inet'
cosmos::params::master_ip: '10.95.236.10'
cosmos::params::master_hostname: 'andromeda01'
cosmos::params::pdihub_client_id: '20f0381a6698c19953d5'
cosmos::params::pdihub_client_secret: 'b11b73f83e7dcf940fec3356d3d0604e3169ab98'
cosmos::params::horizon_password: 'horizon!'
cosmos::params::ssl_authority: 'TID'
cosmos::params::ssl_cert_location: 'https://issuecatid.hi.inet/certsrv'
cosmos::params::ssl_support_name: 'EPG'
cosmos::params::ssl_support_email: 'epg@tid.es'
cosmos::params::ambari_mr_app_master_memory: 1024
cosmos::params::ambari_map_task_memory: 2048
cosmos::params::ambari_map_heap_memory: 1536
cosmos::params::ambari_reduce_task_memory: 3072
cosmos::params::ambari_reduce_heap_memory: 2304
cosmos::params::ambari_yarn_total_memory: 28672
cosmos::params::ambari_yarn_container_min_memory: 128
cosmos::params::ambari_yarn_virtual_physical_memory_ratio: 2.1
cosmos::openvz::network::host_iface: 'bond0.1'
slave_hosts:
    - 'andromeda02'
    - 'andromeda03'
    - 'andromeda04'
    - 'andromeda05'
    - 'andromeda06'
    - 'andromeda07'
    - 'andromeda08'
    - 'andromeda99'
