#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

ambari::params::repo_url: %{cosmos::params::cosmos_repo_platform_url}
cosmos::params::cosmos_subnet: '192.168.63.0'
cosmos::params::cosmos_netmask: '255.255.255.128'
cosmos::params::cosmos_repo_platform_url: 'http://cosmos10.hi.inet/nexus/service/local/yum/repos/releases/production'
cosmos::slave::gateway: "192.168.63.1"
cosmos::slave::ct_gateway: "192.168.63.1"
cosmos::slave::host_key_priv_file: "puppet:///modules/cosmos/environments/%{environment}/%{hostname}_key"
cosmos::slave::ct_key_priv_file: "puppet:///modules/cosmos/environments/%{environment}/%{hostname}_ct_key"
cosmos::params::domain: '.hi.inet'
cosmos::params::master_ip: '192.168.63.19'
cosmos::params::master_hostname: 'orion01'
cosmos::openvz::network::host_iface: 'bond0.1'
slave_hosts:
    - 'orion02'
    - 'orion03'
    - 'orion04'
    - 'orion05'
    - 'orion06'
    - 'orion07'
    - 'orion08'
    - 'orion09'
    - 'orion10'
    - 'orion11'
    - 'orion12'
    - 'orion13'
    - 'orion14'
    - 'orion99'
    - 'orion98'
    - 'orion97'

