#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

ambari::params::repo_url: %{cosmos::params::cosmos_repo_platform_url}
cosmos::params::cosmos_subnet: '10.95.236.0'
cosmos::params::cosmos_netmask: '255.255.255.0'
cosmos::params::cosmos_repo_platform_url: 'http://cosmos10.hi.inet/nexus/service/local/yum/repos/releases/production'
cosmos::params::cosmos_ssl_cert_source: "puppet:///modules/cosmos/environments/%{environment}/certs/%{hostname}_cer.pem"
cosmos::params::cosmos_ssl_key_source: "puppet:///modules/cosmos/environments/%{environment}/certs/%{hostname}_key.pem"
cosmos::slave::gateway: '10.95.236.1'
cosmos::slave::ct_gateway: '10.95.236.1'
cosmos::slave::host_key_priv_file: "puppet:///modules/cosmos/environments/%{environment}/%{hostname}_key"
cosmos::slave::ct_key_priv_file: "puppet:///modules/cosmos/environments/%{environment}/%{hostname}_ct_key"
cosmos::params::domain: '.hi.inet'
cosmos::params::master_ip: '10.95.236.26'
cosmos::params::master_hostname: 'cosmos'
cosmos::params::infinity_url: 'hdfs://orion-infinity.hi.inet'
cosmos::params::pdihub_client_id: 'e2c65e49dd037825a147'
cosmos::params::pdihub_client_secret: '79eb025adcce237a0198614efef91f8edb4a527d'
cosmos::params::horizon_password: 'horizon!!'
cosmos::params::ssl_authority: 'TID'
cosmos::params::ssl_cert_location: 'https://issuecatid.hi.inet/certsrv'
cosmos::params::ssl_support_name: 'EPG'
cosmos::params::ssl_support_email: 'epg@tid.es'
cosmos::params::ambari_yarn_total_memory: 28672
cosmos::params::ambari_yarn_container_min_memory: 3584
cosmos::params::ambari_yarn_virtual_physical_memory_ratio: 2.1
cosmos::params::ambari_map_task_memory: 3584
cosmos::params::ambari_reduce_task_memory: 3584
cosmos::params::ambari_map_heap_memory: 2048
cosmos::params::ambari_reduce_heap_memory: 2048
cosmos::params::ambari_mr_app_master_memory: 1024
cosmos::openvz::network::host_iface: 'bond0.1'
slave_hosts:
    - 'orion02'
    - 'orion03'
    - 'orion04'
    - 'orion05'
    - 'orion06'
    - 'orion07'
    - 'orion08'
    - 'orion09'
    - 'orion10'
    - 'orion11'
    - 'orion12'
    - 'orion13'
    - 'orion14'
    - 'orion15'
    - 'orion16'
    - 'orion17'
    - 'orion18'
    - 'orion19'
    - 'orion20'
    - 'orion21'
    - 'orion22'
    - 'orion23'
    - 'orion24'
    - 'orion25'
    - 'orion26'
    - 'orion27'
    - 'orion28'
    - 'orion29'
    - 'orion30'
    - 'orion31'
    - 'orion32'
    - 'orion33'
    - 'orion34'
    - 'orion35'
    - 'orion36'
    - 'orion37'
    - 'orion38'
    - 'orion39'
    - 'orion40'
    - 'orion41'
    - 'orion99'
    - 'orion98'
    - 'orion97'
    - 'orion96'
    - 'orion95'
    - 'orion94'

