#)
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

cosmos::slave::ip: "192.168.63.37"
cosmos::slave::ct_ip: "192.168.63.101"
cosmos::slave::ct_hostname: "orion-compute15"
cosmos::slave::hardware_profile: 1
cosmos::slave::name: "Orion 15"
cosmos::slave::ram: 32768
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwlbtklj2YoiOcFitaw/9s/NPI4xFhAEHrb8uS1vt66EEU5CfwJaLy0bksGAWlYEELZ+BTybNtCGE4LWufAlgDuPmwtbiz+j51hzCe7E73BRc2P/+Ly4OoaseFOynEq3HslF/+CIF2yl9ethBQwsIJviT817LltkD2vCi2Pm//ctNTwxO2RI5bsvUYw22pPUZaFPM4uMRCS7QTQpa6J/DW5jEMF0oReX0iXT+8rAYrFAgN6pSGB/4VSO5P4ZG6qbJ+M4kagNfB3s4W+bDygcMmAvo/5CCQgQIMhcKDF416sCVg2N24GPujukF0Hcuib+1sBHXxjtMj/Oo0OCamKTS7"
cosmos::slave::ct_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDkbqyPKsNdOfl5mqYOI5XGM/adYQ72JS+SfWXqKjO4yey53xc9sS+IwsKhHliFGkua1cvuUgwan/tye+CbuJ45jnCIsC+rnHRpLPU7BzBNNR1EiKnYB0uqZuOzyVmCj0fJnUlxb1u44Mr07/iVdWX1XBuEXewyDnfeCh6J2gX+gVgj0NKvbvBeoACtBvJSHT1pan4PQtvb5GfSY7XfX5Xidzp2WmW0hISmeJeEmSuoRBB69prgQVTbLOZg3RHX698U7B1nX0snbs45Uwg/kscbB62MRQvINBk33AW5Q5i0a1TwB4pBZlWY0bYCfGm+0nakxbHLZp+Jf1zKdlX+WWDN"
