#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

cosmos::slave::rack: "rack02"
cosmos::slave::ip: "192.168.63.30"
cosmos::slave::ct_ip: "192.168.63.94"
cosmos::slave::ct_hostname: "orion-compute12"
cosmos::slave::hardware_profile: g1-compute
cosmos::slave::name: "Orion 12"
cosmos::slave::ram: 32768
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArXLE3tnDjRCkMQZQKe0YqQwqJrBTHpA/tAVJ1cPKDTZmhyJsJKmaZsdcDhyZUgN0yQjBaKszIdfCwUKp67WVeU/Gb+4sexz4lHBHr8QPGCIDWPdjV7WKYSbtTCfbgjwShf06wa0drPHdhzx8hD1nzJ9LCdQSbIONT1RvfuHTJAhBdvWIlEiHE/731S12zn77p8Td+PSbc06ryImb+8xbkU8ES3SrsKzXi/nHume2RJanhOp1JN9uR+2VlMD6dG3Eeor32Of2NF0J8TsKHEODvJ02/BHAzYFBOHN0cnk/6VWDfJR7yt39z8l4aXojuXYT76Q2sLt96T4nWXeSFEZ3Qw=="
cosmos::slave::ct_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5yUSLQ7DgH/3F4pnNNOZNhE1Jnez1Q/k+KTLKJrp5feNgWiOBNhGyTC16QJgfmJ42nVybLswaIJtrxzWJWTLEV5e5KqyZSc6THKWSrvkqvhRhf6tPdhWlFiRAcApgMKyTRypANJKoJWPlbJGz+2ff4ePs+NnPcxyLYfplZJpTLFWC3Un3T233c8hDscT3+bYvzJ4fo07KS83ssX6Hudn34J3fH6DE3PNuG0jQkv02URO3labXAu8x8A82x0+gmX8G84FeQavpahTMfR2iv9uZH0ptY6eWFkWjvlVf2eInfQI+mA8uV/OLzcNnB37K+kjYvaaQ+wV5tQ0QN2f5msCr"
