#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

cosmos::slave::ip: "192.168.63.36"
cosmos::slave::ct_ip: "192.168.63.100"
cosmos::slave::ct_hostname: "orion-data97"
cosmos::slave::hardware_profile: hdfs-slave
cosmos::slave::name: "Orion 97"
cosmos::slave::ram: 8192
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAs0ou49+DnCHJin4jX0Ki/QZT+lvTucCiIcan4lupJD93ByMMVDW9DuYB9QuIBaddvvj+YqQo1Gs6o2Ajl0EqLcM8usia8U0/8OMpg3aNGC3VOS1+LJrojOoxeDzk55hgy4oRLf30AtJDoTnTwDvpU2HP0bLaJBu5qZL/ONloffK5BdaHcBqxLnmaE/VKPZLApCKaPGqHoC/e137x1JzcOi/gMfVtb0qYRIgyGpOch71qzQgkfyzrIE28PEn6rw8jghaQ/ergeM453DacQNtWubRepuZBgGTEcBxWkD/zicJtgpBKrM4iCIEaPX9afJ7491mG06CkC3pB+h4pbbWiVw=="
cosmos::slave::ct_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Mo1ZrotgGxqy4y2roHVoX+VVbcQKtoN+Xay2BfxDixzmv60tM70YMFPxZGCLiu3+zoi4CCiMQge/olBg74W2dRQ5LpjRDTIWidwc5qH2YZye07Bh+PtD3uUVb6GEJP9gplMjJqZhvnGO7remreKfsaD0BqoXuz9P74s6i5e5utom9BdYOx5Qxs7dZFk1skJfB09MxdT18C26DMWFUQdyu1EzvJsjiB2lu2UeWuWeV6ve9zMtWe/G+W2kemb46QAGR93nADeWHmlvjLxGcWTVs2f4mqC6D5ZEinUdONTDXH9N0osdnqKqmQTZ00n+aLNgxQXZ6pmp6m79tdY93zCJ"
