#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

cosmos::slave::rack: "rack01"
cosmos::slave::ip: "10.95.236.46"
cosmos::slave::ct_ip: "10.95.236.47"
cosmos::slave::ct_hostname: "orion-compute11"
cosmos::slave::hardware_profile: g1-compute
cosmos::slave::name: "Orion 11"
cosmos::slave::ram: 32768
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAve+2wU4wV4VziJO1gaZf6cgf2KA8VFqsVe3Q2+5I8828sPs3WI8FCgJwwOfVGWlGdelUlW1ohuqNgZt9lQHC/vkEA/38hKYf1Kn3t7vDBjGaGHf77CZaJTYJdf9fnauPXufcMDHRvGY/0O9Af0SlthJp/AEZPFL4VkADklHEKO1w8kfEMeRgz3gtl5pYNLYYS4+k7TPWVawmR/tU90mMa3CqCQ+wavcLeVWviW5iDRzSBBDhcJYA5+gbbD5xZgtKjUXnQ0sfazjw1cEPjug1AsyxmbI2NodJsVXGyaBc5mC56fgVkJqpWalcO9NouEcWWsWwGKJrTAfqc/vngZWctQ=="
cosmos::slave::ct_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDC/SpcEAWKVWGxigNctCoTlE69AC33GFzaGhprCc9pCqgm50z+IjUk5qtK5jFYfoxe84MgF+0co++ECVa+ROvBzMxru7UKPG0TAaSHejrjs8t6zNDT27U6ci/Kdf6oSmpkmwMkUinj/Acg8gIPrRc7Hhn7d4r0c0S2XCW76iUhLfv7GS9K7pY8mEXVKJ5ixMmBWLGaFZvYXavM/+uPKPsXMtpJ7GpxDC0JbcDJlelPS5sKoarBK71B2kVFWJMYOO6gDxLKV7/UKJ78rRMcxiWilh6J9T47YVI7v4364AI8ygFcgK2ipdUSEY2Hd8WKXjvMRKvZfliHHLk7Hr1NYu0Z"
