#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

cosmos::slave::rack: "rack02"
cosmos::slave::ip: "192.168.63.20"
cosmos::slave::ct_ip: "192.168.63.84"
cosmos::slave::ct_hostname: "orion-compute02"
cosmos::slave::hardware_profile: g1-compute
cosmos::slave::name: "Orion 02"
cosmos::slave::ram: 32768
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA0iz79wNld20avf6Se/V76rrw56ZYUyyp4WFxL2QWR3Y4hAEBYrFm8H6bVNV8DwipxO6RuPKe02sidfiklMIQkk1Irie2zaxQ3drzxIr+W/oBmz31rs6MiyiQH5UtiQn6b9IsTfjGmkVmeSRyz1ajOw1WAAN9p84M7hrDvoVuLTcFXVCjV+n0hgKfaAVHgVKENEkHQzcZAyUZJqwrlAUmPIgUqgu1FsqTDgt1DanB6r7pxxq10Vu0oPuqhIwJqb9bxXyhOl+AuEVqHkV/1nBjy2W4hJHfFrFLqmz+TxnbF0PTdZJKuYMAwYpE4Dx+CCxd2viaMQHPMXESa/DXID7wkQ=="
cosmos::slave::ct_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCXpjcywDmbcrV2Vx1BsIMtFICXyP0dU8F0ajq4qTQKLwttCq84sqK6fkpxIMMrq/RcPqTO+UqSdHx/3SNTu3hOLKbhvwAYRHcPa4LdXZ4q1C0bQHi+Lj/D6F1mPE0pVzDRQKco4YNWDyD70qYu3C0MTtZAmmuMCwTEDj1O6pkTUYzv5ZbFjzMxPjGeXcn21R/BHxhjIyxBcjjqqd3U6f0JjqxMBji3fTguA8Gbh7DEdW+fwJnXBf1y3vhVClfnr1VHoiZGgG9V84kTx8lZnOhsx8xclLuqgehd8hqzeWia4DEypqMBeG3D6zhDEs5pCHy5bWMyffdoOqACoYDNR9Qj"
