#)
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

cosmos::slave::rack: "rack02"
cosmos::slave::ip: "192.168.63.44"
cosmos::slave::ct_ip: "192.168.63.108"
cosmos::slave::ct_hostname: "orion-compute22"
cosmos::slave::hardware_profile: g1-compute
cosmos::slave::name: "Orion 22"
cosmos::slave::ram: 32768
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8d3ahLLnsRyVUBQ+6x/+MIlv6EVYckgpVmz/UCWY6H/fFqLUuH6VOwFUKu59AxACM/mh36idclL061uYRCuc6SpcMS2+1imRb4ZghKm2uj05VhW+bdS8PEVtQqHz/g4K9d4QjkqYjidtcYJT0BM2aiiOH+Yo1TmbI8XWk8yjC/uRlEOxyII24JDa6YGPLSnwkWVU6dPiNgibM51onqyF4J01DundGoh9351IL1MOtxNY7SI0NK0KYftyzHhvRdkTFWA1x6K4wSMFKEVlBi4I2RXAmIG5b7PaO67ykB3lb3Lt0miVKJrzEV5ENZb18v0ozuzzRiLgvZk+Ht8eHFmHV"
cosmos::slave::ct_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2k30Fm+HjLpEiA/SgrhblVcd7LLUV9kke83rgd0/MH4P1IXbruot+mfzij0xQeAwMv+nY61BeasCGMWCqfAAsZnMY0OVyJJgoCCpNLXg05g3EXW+apFI97SjQeirgIHmVIIatTo8zlKNmfqw4bolXXNKAqM9fq7ek8Pox/uDAfaHq7dtKkXAderpO5Ng+rqIiIs4jmgClndVl3/z0D1ImL3TyYYaljjVlneNEDGQr0s4rvo8kRKg8bFLni/cHaCf4dAwmtcyIN6Q3ffXo1UiTT29zYe8j1+Aevuw6oUwMu4h8wHvM+mw+SHxY9gjH3Yw5fCfYJsO6/XbdJa3+7XrF"
