#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

cosmos::slave::rack: "rack01" 
cosmos::slave::ip: "192.168.63.63" 
cosmos::slave::ct_ip: "192.168.63.127" 
cosmos::slave::ct_hostname: "orion-compute39" 
cosmos::slave::hardware_profile: g1-compute
cosmos::slave::name: "Orion 39" 
cosmos::slave::ram: 32768
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3X4WRicMNGb1VElP2JaeAu0wTyDMdoTxRdUL7Rw1l1UAfCkoyc3GM3aatGvgCUIKqi9+iGqdtxcKegjkgoJI3BCb48W0VGZNKb4eWPvlqrBv7AVGeNROTgydVX+gh1seMJjZQw6RJBhPx7LB4jQos2ZzBo5nx/1un7Q5zsj4EhHpcG1E6M8cdNRXM9pYnwFfWr8uHwDzXxa5wu+nBL3RQgk9Rmv2692ykAGfcF4zX17dw7gkIPJ+XFhDM19uz8Db6kRTDWaYwtXtro3RDA8cJyNTYjhrBtxrn2wqpYky43rIQP3ZPmQ3YBR+UiEwxdFhY/QpUFpYqL+aZngK2JCuH" 
cosmos::slave::ct_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCXjIyyFx8T7HCQEOrh8aA3XJfhC3siWkogmWvMty9SXXDKPzuAzbgfo89MM1piM93iB/KUE/OjfHNyVEFu/k7bunXj5jP27eKXXBq6DziW0FsLBSXKnrlVO+4bN5fybgCIRAuHxVgJovnUzuk7JpCLce0ZvCqOkpuezb4P2fldrLnn/lf/IUn7cyzxrmecMYgvSyyN6ThGctyy6T81P0ttMTLEjvg+zMEIjgHjxwwhMTVlrB3wOtizhuBzAiil9QQsUpxeLbPQ+41++9RDyh1CZ4Jlz/pUFqC0SUyQTJliuc9ExBvE8t2vZfBGYhtdYU1TaGjCWA6Cm0jFc6O9bUIx" 
