#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

cosmos::slave::ip: "192.168.63.21"
cosmos::slave::ct_ip: "192.168.63.85"
cosmos::slave::ct_hostname: "orion-compute03"
cosmos::slave::hardware_profile: g1-compute
cosmos::slave::name: "Orion 03"
cosmos::slave::ram: 32768
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA4upY2TK3CZlvR2fljAdtK2W56rUBJS6MsWQqFlF/c2k2PXCmy5DMig7zIloWPeLmbewkc6LhceVQSigUCog4xaO3LOUvW7A5dzwqDsGhsMjA4iREmNcdkW5VGk6ShQPZhRcY9/029+w5WLfb9nxnWi2U2t4UarjVtp6t1twxM5LvVrAPtDjYQFZB9oxSLImx3tl5pjOfyp0nWnfSCHuBbwdUUaXNsiRJkFLbUUyC7DONaT1/UWAQx3HhbTxsQO+X3h+UX/eb65DyauFzOc3BaLBoaTpKGP0NVkNjMj2BToPPsC6oAH4IyIA8rTyGtwfYOpMjWyr+eyV5n1FCTJMVuw=="
cosmos::slave::ct_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/grFBJy5ue6/ndKwLdTStkxPb65ktBR3ZPeb71cD2Z7T2gshww5Yb9n3BwAEMu0Rsh51MOqW2glfawK7yA/iVSBnPKRFy9eeBtHPHfAmmy1q+usLpu+Q5gcPLe0wP1a4VZdSkr/AXtkRnnizy/h/LjyINy6ESkN7lWpeKyecgXI/2zZZHFNFyxwJEwpXh7FS4abmR0dL1yrAZorqO/cM0v+CXckEtESReuu/ipcA0k421dbrA2e4LOmw4fz1e3bDtlV5V/bZAW20e3arGcNIxqMb8cQdweJ/AyTVruQ7AolWoEFf0otG4SUrYKUgo+t57RQcX0Lm9+XZGDwpU3WCx"
