#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

cosmos::slave::rack: "rack02"
cosmos::slave::ip: "192.168.63.34"
cosmos::slave::ct_ip: "192.168.63.98"
cosmos::slave::ct_hostname: "orion-data99"
cosmos::slave::hardware_profile: hdfs-slave
cosmos::slave::name: "Orion 99"
cosmos::slave::ram: 8192
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEApjQ7Tc/UNJkWf59q9YQtCvTxmu2xfTagRsXq6yuboTVcOtYVIviFFj6KffKudRckxNdm5luS3lkGj52ZPueJxVEkqPpbQon4+KD2Xy0rMsYW9qeZUX6cO0CRY3a4Kg4YmqS/SK5jJrxWPtL9l92w+Yq1L2DU5sDFIrMfPMnVS8BWuHUjQKsIQRvUTnx8/EYFuUhvL+XKYrKJeUbulpeLEkS+ocQsg1wPovTAeQBccM1o/0TbUK+qKC7pZenTVFDCjGvH2FqT7IkbOqnlh73rAhEltH/5ISyA410rYxAyylmpJHCvpEHg8+8eTzV/jiD5Pvz0pXF9m/MRcQQjd7HsmQ=="
cosmos::slave::ct_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDhJzMJKKRjqMxDr7KtFGrcdc1lLEVqUQMY/Xa2BQKrLhmUCaOhGKBvlekl+eFkM96z7grMWbBUImxzy7Rsu1DEwDwIPmHUpAQB4eyxwa/ZPGMYENPlZxt/ONcDjvSnzVDc5h8B7iSkZ+w3g+1trIEgIwrFFoVDYh+zf1LjkLjwgkKqlgFrLL68Bu7vL+db9kQ+UitPB2DOA3o4EgVkZgDeokTIln5ebtr4iNqQmhbEzZl41zhTEb0GyJ6a2RmZmrleQt0T4I/s/tP2aEEinPOSlByg4IJbESnUC5r6vnP47Te92gN+EF/d7AGxL29lg3bliS31oN9jDSfHI2piuxT7"
