#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

cosmos::slave::rack: "rack01" 
cosmos::slave::ip: "192.168.63.53" 
cosmos::slave::ct_ip: "192.168.63.117" 
cosmos::slave::ct_hostname: "orion-compute29" 
cosmos::slave::hardware_profile: g1-compute
cosmos::slave::name: "Orion 29" 
cosmos::slave::ram: 32768
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8dP1ndcAIzEILod4GrWnmpis1TzfVYDxqkGXsygQN6ffjtMGxvNAoKebSit5bVPWwHPunf+R3zmAE00CGWZLhh2w7w82Br78SjDqNGPHLpikcD8gm9FvCQFK68/njo1UTz9ZQarFuOI+WBbvYlM4ae6LIPwzRmEcPaUZmhYL1kTyLeYVA4fFNSxzXkpytLgjMFXidkm/VlxgwVDh79YhDkbJh9TXy4eb6QWbwcIKUVu7HdsHxIGR+YDxut24UEvnKlZd8uVZqvMhy7YvBaWmbmGzV/wJYoKo5S6iUdGoC0W0gpj5k8UkVFvGjKQWZ6tMW1JcY9ntxzNycruA1FW0h" 
cosmos::slave::ct_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCJknbBMnBiDMvB+uRUeC/eMyns74SO1ZndoEI1fsNCgKbasNzG9Ij2RZu2xpngUNpqfA+PYxTMh/z3eoU5KEddgjDUfX2dxRMP9luCc00DZCV+I0K7yy1rhfO9R86Am+HNLJjCgYUkOPEYLvD1X6uiXm70qDU7zlFpqLzO8m+8CSdsWo6bhDksmpr6F8d91toePMvWiF6BucUc8h9mQz9WmONVGWF4QJNJ7/QZoAz/kSgenie09ArJPY9uI98Dd7cKUDIWr9I32zFFG9PCGgfvW8ppnO5fQ6mV4pBdDevVb93z42Zvkuyv304eZw9EXxcJqKZgUWeC5HPR1Tg0Siud" 
