#
# Telefónica Digital - Product Development and Innovation
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# Copyright (c) Telefónica Investigación y Desarrollo S.A.U.
# All rights reserved.
#

cosmos::slave::ip: "192.168.63.23"
cosmos::slave::ct_ip: "192.168.63.87"
cosmos::slave::ct_hostname: "orion-compute05"
cosmos::slave::hardware_profile: 1
cosmos::slave::name: "Orion 05"
cosmos::slave::ram: 32768
cosmos::slave::host_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA38+C85lu5UBYiqQSNO6E1GCJOAqvXeQU6TyJHsTeuTiMaw7sqkIwj7ZBEI8EbQwyO4SEhT9A2ocntLGua9OZMT9zgcQEVI0lni2NJRopupA9AQw1VAXQ1+koZXU7AlhXCrql9pazF6tlq8JeF8rrKyyR7ysUhoKSfxVIlGG8zvB+E8b+3jAu84zgB+rPS0oo4iWTr3ZN6jHI3gK4G1vki7+qOOkZz/CYgugMRARbrrLd9XzZl9nCnTQ2tsOnho/vFul5z7KpxRXkeWwn1yiVHF8h9wvpORbov0pMNgN/x2CIn6wlAYTzurXnHPs/DHMj5CB02wzGU6QvnSMzgj/FHw=="
